### ISSUE TITLE
[Feature] Custom fuel and battery gauge color

### ISSUE THREAD

**Issue by TanYauRei** [ngocjohn/vehicle-info-card#102]
### Short summary

Add custom fuel and battery gauge color

### Detailed description

Hi there! Thank you very much for your contributions! I have a feature request for custom fuel and battery gauge colors. You have added them in the vehicle status card but not the mercedes card. Thanks!!🙏

**Comment by ngocjohn** [comment]
Hi @TanYauRei do you mean just add custom color select for progress bars or add completely new ones with custom entities?

**Comment by TanYauRei** [comment]
Just the colors :) to be able to differentiate between fuel and battery (you cannot do that with card mod). If you would also be able to change the colors of the (standard) buttons that would be super as well! (now they are linked to the primary-text-color and for custom colors i cannot manage to change the background of the icon)

**Comment by ngocjohn** [comment]
> Just the colors :) to be able to differentiate between fuel and battery (you cannot do that with card mod).

Hi @TanYauRei , if you have card-mod, you can edit styles through it...

each button has its own id, which you can modify their child element.. in this similar way, for progress colors there is attribute [electric] for electric range.. 

look at the example.. 
```yaml
type: custom:vehicle-info-card
card_mod:
  style:
    vehicle-buttons: # customize buttons container
      $: |
        .grid-item { 
          background: midnightblue !important;
        }
        #button-tripCards .icon-background {
          background-color: orange !important;
        }
        #button-vehicleCards .icon-background {
          background-color: green !important;
        }
    .: | # progress container
      .combined-info-box {
        .fuel-level-bar[electric]  {
          background-color: red !important;
        }
        .fuel-level-bar  {
          background-color: purple !important;
        }
      }
```
![CleanShot 2025-01-05 at 16 35 00](https://github.com/user-attachments/assets/f1add26c-c8e7-475f-8ebf-9f3b56d01a1f)
