### ISSUE TITLE
[Bug]: Can't find variable: TouchEvent - Safari

### ISSUE THREAD

**Issue by ReneNulschDE** [ngocjohn/vehicle-info-card#132]
### Short summary 📝

Error is logged in HA-log after clicking on Services, Security

### Detailed description 📋

Safari only
```

2025-04-17 08:04:32.481 ERROR (MainThread) [frontend.js.modern.202504110] Uncaught error from Safari 18.4 on macOS 10.15.7
ReferenceError: Can't find variable: TouchEvent
s (/hacsfiles/vehicle-info-card/vehicle-info-card.js:1615:2620)

```

### Version 📦

v1.8.1

### Card Configuration

```yaml
type: custom:vehicle-info-card
name: Mercedes Vehicle Card
entity: sensor.l_qg_7769_car
model_name: GLA 180 Sport Utility Vehicle
selected_language: system
show_slides: false
show_map: true
show_buttons: true
show_header_info: true
show_background: true
enable_map_popup: true
enable_services_control: true
show_error_notify: true
device_tracker: device_tracker.l_qg_7769_device_tracker
map_popup_config:
```

### Environment 🌐

Safari 18.4 on macOS 10.15.7

### Logs and screenshots 📂

![Image](https://github.com/user-attachments/assets/d1eb2b75-3d21-4d44-b895-4c64f1278783)
