### ISSUE TITLE
[Bug]: Card not displaying

### ISSUE THREAD

**Issue by cinzas** [ngocjohn/vehicle-info-card#154]
### Short summary 📝

Card is not displaying using basic yaml confi

### Detailed description 📋

Even using basic Yaml file, after latest update the card is not displaying.
If I add it via GUI, it shows.

Yaml used.

`       - type: custom:vehicle-info-card
         entity: sensor.mercedes_car
         name: Mercedes-AMG E300de
`

### Version 📦

v1.8.3-beta.1

### Card Configuration

```yaml
type: custom:vehicle-info-card
entity: sensor.mercedes_car
name: Mercedes-AMG E300de
```

### Environment 🌐

Chrome on ubuntu

### Logs and screenshots 📂

![Image](https://github.com/user-attachments/assets/f88b49d3-9fd5-4ec7-8e6d-a96ea3dbbec6)
