### ISSUE TITLE
[Bug]: Card width conflict with custom layout

### ISSUE THREAD

**Issue by Pjarbit** [ngocjohn/vehicle-info-card#162]
### Short summary 📝

Vehicle Card expands into infinity.

### Detailed description 📋

I am using browser mod with a custom layout on a panel card.  I have all home assistant files updated.  When using the newest version in with the map (although the map is difficult to see) the card has the mercedes emblem fly out and looks great until the card starts expanding into infinity - horizontally.  it pushes all other columns to the right.  My custom layout has 8 columns with 150px 30px 1fr 15px 1fr 15px 1fr 30px.  

### Version 📦

v1.11.0

### Card Configuration

```yaml
CARD HAVING ISSUES IN VIDEO

type: custom:vehicle-info-card
entity: sensor.pja1_car
name: PJA1 Mercedes Benz
show_slides: true
show_map: true
show_buttons: true
show_background: true
enable_map_popup: true
enable_services_control: true
theme: Mushroom Square Shadow
mode: dark
services:
  auxheat: true
  charge: true
  doorsLock: true
  engine: true
  preheat: true
  sendRoute: true
  sigPos: true
  sunroof: true
  windows: true
map_popup_config:
  theme_mode: dark
  default_zoom: 12
selected_theme:
  theme: Mushroom Square Shadow
  mode: dark
device_tracker: device_tracker.pja1_device_tracker
model_name: MY23 EQE350X4
selected_language: en
card_mod:
  style: |
    ha-card {
      background-color: rgba(67, 73, 82, 1);
      box-shadow: 12px 12px 24px rgba(0, 0, 0, 0.5),
                  -4px -4px 8px rgba(255, 255, 255, 0.1),
                  inset -4px -4px 8px rgba(0, 0, 0, 0.2),
                  inset 4px 4px 8px rgba(255, 255, 255, 0.2);
      border-radius: 10px;
    }
```

### Environment 🌐

chrome on windows 11 everything up to date

### Logs and screenshots 📂

https://github.com/user-attachments/assets/1e1ea1c2-bcc2-4b01-bd42-a1f18cab299b
