### ISSUE TITLE
[Bug] How to download car top view for tier custom background

### ISSUE THREAD

**Issue by salvatoreboemia** [ngocjohn/vehicle-info-card#94]
### Short summary 📝

download car top view for tier custom background

### Detailed description 📋

Hi

I tried to download through mercedes API the image of my car top view, but without success

do you know how to do that?

thanks

### Version 📦

v1.6.0

**Comment by ngocjohn** [comment]
Hi @salvatoreboemia you can download images directly via HA services. 
![CleanShot 2024-12-11 at 12 58 59@2x](https://github.com/user-attachments/assets/c6434d03-a92a-4501-9c11-b972a6555d2f)

**Comment by salvatoreboemia** [comment]
> Hi @salvatoreboemia you can download images directly via HA services. ![CleanShot 2024-12-11 at 12 58 59@2x](https://private-user-images.githubusercontent.com/96962827/394729727-c6434d03-a92a-4501-9c11-b972a6555d2f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MTg3MjMsIm5iZiI6MTczMzkxODQyMywicGF0aCI6Ii85Njk2MjgyNy8zOTQ3Mjk3MjctYzY0MzRkMDMtYTkyYS00NTAxLTljMTEtYjk3MmE2NTU1ZDJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjExVDEyMDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwZDkwNmIzOGJlMDhjZWE1NzhiZjNiNzU3YjU1YTNkZjY5NmQxZmYzZTdkM2YxMzFiMDZmMzk5YmUxNDM5ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ovom9pfJJ1YD_Y_Yek4WiAsVj2iAI1fmqvDfCgtkZcA)

hi @ngocjohn I tried to run action with my VIN but nothing appen

**Comment by ngocjohn** [comment]
@salvatoreboemia the images is downloaded to folder custom_components/mbapi2020/resources/vin.zip Take a look over there.

**Comment by salvatoreboemia** [comment]
Hi @ngocjohn  thanks a lot

I downloaded the top view (I need to resize it to 450px maximum for the tire view)

But how can I use the red part of the car? in your YAML how can I use all the red parts?

thanks again

**Comment by ngocjohn** [comment]
This is the picture element card, the instruction is also in the readme.  https://community.home-assistant.io/t/mercedes-me-component/41911/1809

**Comment by salvatoreboemia** [comment]
Hi @ngocjohn 

quiet complex but I did it

Now I have a separate card (very long yaml) with this info

```
type: picture-elements
image: local/177000_car2.png
transform: translate(-50%, -50%)
elements:
  - type: image
    entity: sensor.XXX_door_frontleft
    state_image:
      Open: local/177000_door_frontleft_open.png
      Unlocked: local/177000_door_frontleft_unlock.png
      Locked: null

...

etc

```

<img width="326" alt="Screenshot 2024-12-11 at 14 34 54" src="https://github.com/user-attachments/assets/a3a88b1a-7e5a-4b83-9a2f-c6315a94b8b4">


But it's possible to have this custom card inside your tire custom card? I tried but no success

Thanks

**Comment by salvatoreboemia** [comment]
Super done!

Last thing, is it possible also to add 2 entity (like yours 2 pressure tire near) If I triy to add double entity I didn't see

```
tyre_button:
  enabled: true
  primary: Pressione ruote e status
  icon: mdi:tire
  hide: false
  secondary: ""
  button_action: {}
  entity: 
    - sensor.XXX_tire_pressure_front_right
    - sensor.XXX_tire_pressure_front_left

```
